version: "3"
networks:
  nginx:
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx
    ports:
      - 5000:80
  server:
    image: httpd:2.4
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    networks:
      - nginx
