version: "3"
networks:
  nginx:
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./assets:/nginx-test/assets/
    networks:
      - nginx
    ports:
      - 5000:80
  server1:
    image: httpd:2.4
    volumes:
      - ./server1:/usr/local/apache2/htdocs/
    networks:
      - nginx
  server2:
    image: httpd:2.4
    volumes:
      - ./server2:/usr/local/apache2/htdocs/
    networks:
      - nginx
  server3:
    image: httpd:2.4
    volumes:
      - ./server3:/usr/local/apache2/htdocs/
    networks:
      - nginx
